### ISSUE TITLE
It does not work at all or I am doing something wrong

### ISSUE THREAD

**Issue by conwilcon** [Blogshot/trip-sitter#12]
No matter what I do, the program does not work.

![image](https://user-images.githubusercontent.com/81932678/113521951-fede8500-956a-11eb-948b-1555b9ed2916.png)

**Comment by Blogshot** [comment]
Most likely you are trying to convert an encrypted .synth file.

You can check this by extracting the .synth via 7zip, for example. If it asks for a password, the .synth is encrypted and can't be converted.

Nevertheless, the error message clearly shouldn't report "success"; I'll fix that soon.

If the file is not encrypted and can be extracted without asking for a password, please reply again and I'll take a closer look at this.
